# Generated by Django 3.0.7 on 2021-03-26 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0007_auto_20210116_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awareness', models.CharField(max_length=20)),
                ('duration', models.CharField(blank=True, max_length=200, null=True)),
                ('disease', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=200, null=True)),
                ('medications', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, max_length=2000, null=True)),
                ('date', models.DateField(null=True)),
                ('owner_username', models.CharField(max_length=300, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='episode', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='set',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='setimage',
            name='set',
        ),
        migrations.RemoveField(
            model_name='setnotes',
            name='setImage',
        ),
        migrations.DeleteModel(
            name='Cluster',
        ),
        migrations.DeleteModel(
            name='Set',
        ),
        migrations.DeleteModel(
            name='SetImage',
        ),
        migrations.DeleteModel(
            name='SetNotes',
        ),
    ]
