# Generated by Django 3.0.7 on 2021-03-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20210326_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='condition',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
