# Generated by Django 3.0.7 on 2021-03-26 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_episode_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
