# Generated by Django 3.0.7 on 2021-03-26 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20210327_0055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='date',
            new_name='time',
        ),
    ]
