# Generated by Django 3.0.7 on 2021-03-26 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20210327_0057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='time',
        ),
    ]
